application: ymswiki
version: 1-0-2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /gae-wiki-static/
  static_dir: gaewiki/static
- url: /favicon.ico
  static_files: gaewiki/static/favicon.ico
  upload: gaewiki/static/favicon.ico
- url: .*
  script: gaewiki.app

#- url: /static/
#  static_dir: static
#- url: .*
#  script: handlers.py

# builtins:
# - datastore_admin: on
